// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/alertmanager/alertmanager.proto

package alertmanager

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for AlertManager service

func NewAlertManagerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "AlertManager.CreateAlertInfo",
			Path:    []string{"/alertmanager/v1/alerts"},
			Method:  []string{"POST"},
			Body:    "*",
			Handler: "rpc",
		},
	}
}

// Client API for AlertManager service

type AlertManagerService interface {
	CreateAlertInfo(ctx context.Context, in *CreateAlertInfoReq, opts ...client.CallOption) (*CreateAlertInfoResp, error)
}

type alertManagerService struct {
	c    client.Client
	name string
}

func NewAlertManagerService(name string, c client.Client) AlertManagerService {
	return &alertManagerService{
		c:    c,
		name: name,
	}
}

func (c *alertManagerService) CreateAlertInfo(ctx context.Context, in *CreateAlertInfoReq, opts ...client.CallOption) (*CreateAlertInfoResp, error) {
	req := c.c.NewRequest(c.name, "AlertManager.CreateAlertInfo", in)
	out := new(CreateAlertInfoResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AlertManager service

type AlertManagerHandler interface {
	CreateAlertInfo(context.Context, *CreateAlertInfoReq, *CreateAlertInfoResp) error
}

func RegisterAlertManagerHandler(s server.Server, hdlr AlertManagerHandler, opts ...server.HandlerOption) error {
	type alertManager interface {
		CreateAlertInfo(ctx context.Context, in *CreateAlertInfoReq, out *CreateAlertInfoResp) error
	}
	type AlertManager struct {
		alertManager
	}
	h := &alertManagerHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "AlertManager.CreateAlertInfo",
		Path:    []string{"/alertmanager/v1/alerts"},
		Method:  []string{"POST"},
		Body:    "*",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&AlertManager{h}, opts...))
}

type alertManagerHandler struct {
	AlertManagerHandler
}

func (h *alertManagerHandler) CreateAlertInfo(ctx context.Context, in *CreateAlertInfoReq, out *CreateAlertInfoResp) error {
	return h.AlertManagerHandler.CreateAlertInfo(ctx, in, out)
}
